executors:
  nodejs:
    docker:
      - image: 'circleci/node:12.11.0'
    working_directory: ~/github-shortcuts

jobs:
  build:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: download dependencies
          command: npm install
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: compile
          command: npm run build
      - run:
          name: Zip the extension
          command: zip github-shortcuts.zip -r dist
      - persist_to_workspace:
          paths:
            - github-shortcuts.zip
          root: ~/github-shortcuts

orbs:
  cws: sugarshin/chrome-webstore@0.0.3

version: 2.1

workflows:
  build_publish:
    jobs:
      - build
      - cws/upload:
          attach-workspace: true
          auto-publish: true
          checkout: false
          executor: nodejs
          extension-id: pdeaikmjefgminiagmbdhjlmoaoobbjc
          source: github-shortcuts.zip
          workspace-root: ~/github-shortcuts
          requires:
            - build
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
